name: Pack React Project
on: push

jobs:
  npm-build:
    name: Npm-build Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Load Repo
        uses: actions/checkout@v4
      - name: Install Dependency
        run: npm install
      - name: Project Pack
        run: npm run build