name: Pack React Project
on: push

permissions:
  contents: write

jobs:
  npm-build:
    name: Npm-build Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Load Repo
        uses: actions/checkout@v4
      - name: Install Dependency & Project Pack
        run: |
          npm install
          npm run build
      - name: Deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build